### ISSUE TITLE
use loaded date instead of original date in rat/human->mouse orthology load

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#37]
From: https://github.com/geneontology/go-site/issues/2043#issuecomment-1966581332

GO_REF:0000096 J:155856 Rat to mouse / GO_REF:0000119. J:164563. Human to mouse
Annotation date: 2/23 flie used the original human/Rat EXP date for the ISO date. Should we use the actual loading date?

**Comment by sierra-moxon** [comment]
according to the GPAD 2.0 spec, this field is the "annotation date":
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

@kltm - should we use the date the human/rat annotation was converted to a mouse annotation via orthology, or the date the original annotation was made here?

**Comment by kltm** [comment]
It may depend on the evidence used, but likely the date the “new” annotation was made—ie the date of the orthology xfer computation. This helps capture additional information, as the annotation may be old, but the orthology new.
