### ISSUE TITLE
investigate missing annotations from MGI imports pipeline - EXP "GO_Central", and "GOC" annotations should not have been exluded from the load

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#38]
from Li via: 
https://github.com/geneontology/go-site/issues/2043

```
IKR examples:
UniProtKB P60154 Rnase9 NOT|enables GO:0004540 PMID:15676279 IKR F Inactive ribonuclease-like protein 9 Rnase9 protein taxon:10090 20150710 GO_Central
UniProtKB Q5GAM7 Rnase13 NOT|enables GO:0004540 PMID:15676279 IKR F Probable inactive ribonuclease-like protein 13 Rnase13 protein taxon:10090 20150710 GO_Central
```

**Comment by sierra-moxon** [comment]
```
SMoxon@SMoxon-M82 gopreprocess % grep "UniProtKB:P60154" mgi-src.gpi      
MGI:MGI:3057273	Rnase9	ribonuclease, RNase A family, 9 (non-active)		SO:0001217	NCBITaxon:10090				UniProtKB:P60154	
PR:P60154	mRNASE9	inactive ribonuclease-like protein 9 (mouse)	mRNASE9	PR:000000001	NCBITaxon:10090	MGI:MGI:3057273			UniProtKB:P60154
```

this might have to do with a non-1:1 mapping..investigating

**Comment by sierra-moxon** [comment]
the original annotation in GOA for the first IKR example is: 
```
UniProtKB	P60154	Rnase9	NOT|enables	GO:0004540	PMID:15676279	IKR		F	Inactive ribonuclease-like protein 9	Rnase9	protein	taxon:10090	20150710	GO_Central		
```
it has an `assigned_by` of `GO_Central` ... there was a requirement for this ingest to ignore annotations in protein to GO that are from "MGI", "GO_Central", or "GOC".

I think my script is behaving as designed, so I guess the next question is: if GO_Central provides this, we need to figure out where?  (maybe it's in a different form or to a different ID or included in some other ingest? - asking around on my side - do you have any insight?)

**Comment by sierra-moxon** [comment]
The IKR issue that worries me is that in [the GOA annotation records](https://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse.gaf.gz) the provider as "GO_Central", however, the final GPAD and GAF produced by this test pipeline are missing these annotations.

Tracing the annotation, it seems like it's something like this:
GO_Central (?in which GO internal pipeline or annotation step is this originally generated?) -> Protein2GO -> GoPreprocess (skip it) -> GO Pipeline -> final GPAD/GAF (missing)

So where is the original location of this annotation? (e.g. noctua, some sort of external ingest to noctua, etc.)

**Comment by kltm** [comment]
To clarify a concrete example for the sake of @kltm 
`UniProtKB Q5GAM7 Rnase13 NOT|enables GO:0004540 PMID:15676279 IKR F Probable inactive ribonuclease-like protein 13 Rnase13 protein taxon:10090 20150710 GO_Central`
This annotation is currently found in GO output products. However, given the rules of the (in progress) MGI pre-process import step from Protein2GO, anything that has source `GO_Central` is dropped. With this, our ingest is behaving as expected. The solutions would be to either 1) change the source in the p2go upstream or 2) change the rules if this is important.

**Comment by kltm** [comment]
@LiNiMGI @ukemi how should we proceed on https://github.com/geneontology/gopreprocess/issues/38#issuecomment-1967899688 ?

**Comment by LiNiMGI** [comment]
We looked further into the GOA_mouse file:

All annotations with "assigned by:GO_Central" are: 
GO_REF:0000033 IBAs/PAINT annotations
And 66 annotations that were mostly made or modified by Pascale with evidence code: IDA, IMP, IPI, IKR, ISS.

MGI think we should include them in the load.

So maybe we need to modify the rules of import to: 
only exclude GO_REF:0000033 with "assigned by:GO_Central"
or
include IDA, IMP, IPI, IKR, ISS annotations with "assigned by:GO_Central"

Thanks,
Li

**Comment by sierra-moxon** [comment]
from managers call:
we thought the only thing coming was PAINT annotations but it turns out we get these from other places too

action: new rule: only exclude GO_REF:0000033 with "assigned by:GO_Central"


We think these are PAINT, but manual PAINT and GO_Central is a curator in protein2GO - these are experimental annotations from Pascal.  Could also be some experimental evidence codes from other curators.

**Comment by sierra-moxon** [comment]
new file generated http://skyhook.berkeleybop.org/full-issue-325-gopreprocess/annotations/mgi.gpad.gz
