### ISSUE TITLE
convert abstract and title text of GO_REF:0000096 to describe new preprocessing pipeline here instead of MGI curation process

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#5]
- also make sure we should be using GO_REF:0000096 for both human->mouse and rat->mouse ortholog annotations?

**Comment by ukemi** [comment]
Note that GO_ref:0000096 corresponds to both J:164563 (human ISO load) and J:155856 (rat ISO load).

The human abstract at MGI is currently:
Experimental data from the human  gene association files are downloaded from the GO Consortium website (http://www.geneontology.org/). Human  annotations with experimental evidence codes (IDA, IMP IPI, IGI, and EXP) are automatically associated with the orthologous mouse genes with an evidence code of ISO (Inferred from Sequence Orthology; for more information about GO evidence codes, their meaning and how they are used, go to the GO Consortium evidence code documentation at http://www.geneontology.org/GO.evidence.shtml).  The original reference PubMed ID that provides the source data for the human annotation is maintained in the MGI system. The laboratory mouse is used as models for the study of human diseases. Both the Mouse Genome Database (MGD) and HGNC  have extensive procedures in place, overseen by expert curation, to establish orthology relationships between their genes. Both MGI and GO Annotation at EBI (UniProtKB-GOA) engage in curated Gene Ontology (GO) annotation using the experimental literature available for each organism and adhering rigorously to the guidelines set forth by the GOC.

The rat abstract at MGI is:
Both the Mouse Genome Database (MGD) and the Rat Genome Database (RGD)  have extensive procedures in place, overseen by expert curation, to establish orthology relationships  between their genes. Furthermore, each database engages in curated Gene Ontology (GO)  annotation using the experimental literature available for each organism, and adhering rigorously to the guidelines set forth by the GOC. Experimental data from the rat gene association files are downloaded from the GO Consortium website (http://www.geneontology.org/).  Rat annotations with experimental evidence codes (IDA, IMP IPI, IGI or IEP) are automatically associated with the orthologous mouse genes with an evidence code of ISO (Inferred from Sequence Orthology; for more information about GO evidence codes, their meaning and how they are used, go to the GO Consortium evidence code documentation at http://www.geneontology.org/GO.evidence.shtml). The original reference PubMed ID  that provides the source data for the rat annotation is maintained in the MGI system.

GO_REF:0000096 is: Automated transfer of experimentally-verified manual GO annotation data to close orthologs.
Mouse Genome Database (MGD), The HUGO Gene Nomenclature Committee (HGNC), and Rat Genome Database (RGD) have extensive procedures in place, overseen by expert curation, to establish orthology relationships between their genes. The Experimentally based annotations annotated by each group (IDA, IMP IPI, IGI, and EXP) are used to provide annotations to the respective mouse and rat orthologs, and given the ISO evidence code and an entry in the inferred_from field to indicate the orthologous entity.

Note that the GO_REF covers both rat and human. I suggest that we retain the GO_REF and modify its text to reflect the new methodology using The Alliance Orthology calls and sequence assignments made in MGI.

**Comment by ukemi** [comment]
Draft new GO_REF:0000096

Automated transfer of experimentally-verified manual GO annotation data to close orthologs.
Mouse Genome Database (MGD) and The Alliance of Genome Resources have extensive procedures in place to establish orthology relationships between genes. The experimentally-based annotations provided by model-organism groups (IDA, IMP IPI, IGI, and EXP) are used to provide annotations to the respective orthologs, and given the ISO evidence code and an entry in the inferred_from field to indicate the orthologous entity.

**Comment by kltm** [comment]
@LiNiMGI Is there a current state on this?

**Comment by LiNiMGI** [comment]
@sierra-moxon 
Would you please double check the abstracts for the GO_REFs that are being used to make sure they reflect how the pipeline is working? thanks, Li

**Comment by sierra-moxon** [comment]
@pkalita-lbl - what to I do here?  :)

**Comment by kltm** [comment]
@pkalita-lbl For context, we want to make some changes to the GO_REFs for this project, but don't want to weird what you have going on. Would it be better to just stick to the old SOP, or do the old and new at the same time to save you the trouble of syncing later?

**Comment by pkalita-lbl** [comment]
With https://github.com/geneontology/go-site/pull/2253 being merged in, I'd appreciate that if you need to an update an abstract that you update it in _both_ the `metadata/gorefs/goref-NNNNNNN.md` and `metadata/gorefs.yaml` file. If you only update the Markdown file it’s not the end of the world, I’ll get them sync’d up later. We’re just in a bit of a multiple-sources-of-truth situation until [this project](https://github.com/orgs/geneontology/projects/88) wraps up.

**Comment by pgaudet** [comment]
@pkalita-lbl After you review the PR (and merge) for the yaml file, this ticket can be closed.

**Comment by pkalita-lbl** [comment]
I reviewed and merged https://github.com/geneontology/go-site/pull/2259
