### ISSUE TITLE
Do not set the date annotated on the Protein to GO annotations, instead inherit this date from the original files.

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#62]
from @LiNiMGI 👍 

Annotation date for the below annotations should not be changed to the loading date, we should keep the original annotation date:
MGI:MGI:101757 | RO:0001025 | GO:0005829 | Reactome:R-MMU-482767 | ECO:0000304 | 3/19/24 | Reactome |   |   |  
MGI:MGI:101757 | RO:0001025 | GO:0030027 | PMID:25107909 | ECO:0000314 | 3/19/24 | UniProt |   |   |  
MGI:MGI:101757 | RO:0002327 | GO:0005102 | PMID:24052308 | ECO:0000353 | UniProtKB:P97484 | 3/19/24 | ARUK-UCL | BFO:0000066(UBERON:0001890)
MGI:MGI:101757 | RO:0002331 | GO:0030836 | PMID:23921380 | ECO:0000314 | 3/19/24 | CACAO |   |   |  
MGI:MGI:101781 | RO:0002327 | GO:0005515 | PMID:16533813 | ECO:0000353 | UniProtKB:P25100 | 3/19/24 | IntAct
MGI:MGI:101782 BFO:0000050 GO:0034706 GO_REF:0000114 ECO:0000266 ComplexPortal:CPX-314 3/19/24 ComplexPortal

I think these are all from the GOA mouse file.

we should only change the date of rat to mouse/human to mouse.

**Comment by LiNiMGI** [comment]
@sierra-moxon 
yes, just checked the 2024-03-20 file, all the date for annotation in protein to go file fixed! thanks!  Li
