### ISSUE TITLE
update dev-base docker image to include a more recent version of python and optional poetry

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/gopreprocess#9]

**Comment by kltm** [comment]
Noting that this is to track updates to ontobio which require a bump on python version.

**Comment by dustine32** [comment]
Noting that the [first run](https://build.geneontology.org/job/geneontology/job/pipeline/job/master/737) of the new `dev-base` docker image on `pipeline/master` has finished without error (as far as we can tell).
